module.exports = {
  projects: [
    '<rootDir>/apps/aws-console',
    '<rootDir>/libs/vpc/feature-shell',
    '<rootDir>/libs/vpc/feature-dashboard',
    '<rootDir>/libs/vpc/subnets/feature-shell',
    '<rootDir>/libs/vpc/subnets/feature-list',
    '<rootDir>/libs/vpc/subnets/feature-create',
    '<rootDir>/libs/shared/subnets/data-access',
    '<rootDir>/libs/shared/ui-services-navbar',
    '<rootDir>/libs/shared/ui-routing',
    '<rootDir>/libs/shared/util-routing',
    '<rootDir>/apps/svc-vpcs',
    '<rootDir>/libs/shared/subnets/domain',
    '<rootDir>/libs/shared/security-groups/feature-shell',
    '<rootDir>/libs/shared/security-groups/feature-list',
    '<rootDir>/libs/shared/security-groups/feature-create',
    '<rootDir>/libs/shared/security-groups/data-access',
    '<rootDir>/libs/shared/security-groups/domain',
  ],
};
